stages:          # Define the stages of the pipeline
  - build
  - test
  - deploy

# Build stage
build:
  stage: build
  script:
    - echo "Hello, World! from Build Stage"

# Test stage
test:
  stage: test
  script:
    - echo "Hello, World! from Test Stage"

# Deploy stage
deploy:
  stage: deploy
  script:
    - echo "Hello, World! from Deploy Stage"
